Ki-We/kiwes_front

Kiwes/package-lock.json, Kiwes/src/components/exitFailModal.tsx, Kiwes/src/components/exitModal.tsx, Kiwes/src/components/kickedOutModal.tsx, Kiwes/src/pages/ChatBubbleMine.tsx, Kiwes/src/pages/ChatBubbleOther.tsx, Kiwes/src/pages/ChatMain.tsx, Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/utils/commonInterface.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: change2

README.md
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> docs: Change readme.md for test git user

Kiwes/src/pages/Login.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> 카카오 자동 로그인 로직 변경

Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/pages/ChatTest.tsx, Kiwes/src/pages/Login.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> Success chat optimize

Kiwes/src/global.ts, Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/pages/ChatTest.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Change input css

Kiwes/src/components/AlarmList.tsx, Kiwes/src/components/ApprovalList.tsx, Kiwes/src/components/BoardList.tsx, Kiwes/src/components/alarm/AlarmList.tsx, Kiwes/src/components/alarm/ApprovalList.tsx, Kiwes/src/components/alarm/ApprovalRequst.tsx, Kiwes/src/components/alarm/RequestList.tsx, Kiwes/src/components/alarm/WaitingList.tsx, Kiwes/src/components/layout/AlarmStack.tsx, Kiwes/src/components/layout/BottomTab.tsx, Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/pages/AlarmPage.tsx, Kiwes/src/pages/WishPage.tsx, Kiwes/src/utils/commonInterface.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat:approval

Kiwes/src/components/BoardList.tsx, Kiwes/src/components/atoms/ListComponent.tsx, Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/components/search/SearchHeader.tsx, Kiwes/src/components/search/initSerch.tsx, Kiwes/src/components/search/searchBtn.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/Search.tsx, Kiwes/src/utils/restapi.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Success to search component

Kiwes/src/components/BoardList.tsx, Kiwes/src/pages/Search.tsx, Kiwes/src/pages/WishPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Fix bug

Kiwes/src/components/atoms/ListComponent.tsx, Kiwes/src/components/search/initSerch.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Fix Key map error

Kiwes/src/pages/Search.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> edit search logic

Kiwes/assets/PrivacyPolicy.html, Kiwes/assets/Terms.html, Kiwes/package-lock.json, Kiwes/package.json, Kiwes/src/components/alarm/AlarmComponent.tsx, Kiwes/src/components/alarm/AlarmList.tsx, Kiwes/src/components/alarm/ApprovalList.tsx, Kiwes/src/components/layout/AlarmStack.tsx, Kiwes/src/components/layout/ApprovalStack.tsx, Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/pages/AlarmPage.tsx, Kiwes/src/pages/ClubPage.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/ProfilePage.tsx, Kiwes/src/pages/Search.tsx, Kiwes/src/pages/SettingPage.tsx, Kiwes/src/utils/commonInterface.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat:alarm&Setting

Kiwes/src/components/LogoutModal.tsx, Kiwes/src/pages/SettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat:logout

Kiwes/src/components/BoardList.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:BoardList

Kiwes/src/components/BoardList.tsx, Kiwes/src/components/alarm/AlarmList.tsx, Kiwes/src/components/atoms/ListComponent.tsx, Kiwes/src/components/layout/BottomTab.tsx, Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/components/layout/Header.tsx, Kiwes/src/pages/Login.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/PostClub.tsx, Kiwes/src/pages/Search.tsx, Kiwes/src/pages/SettingPage.tsx, Kiwes/src/pages/UploadImageTest.tsx, Kiwes/src/utils/commonInterface.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:createMeet

Kiwes/android/app/src/main/AndroidManifest.xml, Kiwes/src/components/alarm/ApprovalRequst.tsx, Kiwes/src/components/post/SetupDetail1.tsx, Kiwes/src/pages/MyPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:search&post

Kiwes/src/components/BoardList.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:BoardList All Clear

Kiwes/src/components/clubdetail/QnAList.tsx, Kiwes/src/components/clubdetail/ReivewErrorModal.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:reviewDelelteLogic

Kiwes/src/components/BoardDefaultList.tsx, Kiwes/src/utils/commonInterface.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Edit location

Kiwes/App.tsx, Kiwes/src/components/layout/DefaultStack.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:deletingNoticePage

Kiwes/src/components/atoms/roundBtn.tsx, Kiwes/src/components/club/ClubList.tsx, Kiwes/src/components/club/ClubListDetail.tsx, Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx, Kiwes/src/pages/WishPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Fix club detail hashtag

Kiwes/src/components/BoardDefaultList.tsx, Kiwes/src/components/BoardList.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Change main popular hashtag

Kiwes/App.tsx, Kiwes/src/redux/actions/ActionTypes.ts, Kiwes/src/redux/actions/index.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Redux

Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Re-Edit Home ratio styles

Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/OtherUserPage.tsx, Kiwes/src/pages/ReviewPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Change mypage code

Kiwes/package-lock.json, Kiwes/package.json, Kiwes/src/components/BoardList.tsx, Kiwes/src/components/club/ClubListDetail.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: 0206 Edit Home Styles

Kiwes/src/components/club/ClubList.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Change detail css

Kiwes/android/link-assets-manifest.json, Kiwes/ios/Kiwes.xcodeproj/project.pbxproj, Kiwes/ios/Kiwes/Info.plist, Kiwes/ios/link-assets-manifest.json, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Update Home & ClubDetail

Kiwes/src/components/exitFailModal.tsx, Kiwes/src/components/exitModal.tsx, Kiwes/src/components/kickedOutModal.tsx, Kiwes/src/components/myBubbleLongpressModal.tsx, Kiwes/src/components/otherBubbleLongpressModal.tsx, Kiwes/src/components/translateModal.tsx, Kiwes/src/pages/ChatBubbleMine.tsx, Kiwes/src/pages/ChatBubbleOther.tsx, Kiwes/src/pages/ChatBubbleSystem.tsx, Kiwes/src/pages/ChatMain.tsx, Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/OtherUserPage.tsx, Kiwes/src/pages/ProfileSettingPage.tsx, Kiwes/src/pages/ReviewBubble.tsx, Kiwes/src/pages/basicSetting/InterestLanguageSettingPage.tsx, Kiwes/src/pages/basicSetting/InterestTopicSettingPage.tsx, Kiwes/src/pages/basicSetting/NationDetailSettingPage.tsx, Kiwes/src/pages/basicSetting/NationSettingPage.tsx, Kiwes/src/pages/profileSetting/BirthdaySettingPage.tsx, Kiwes/src/pages/profileSetting/GenderSettingPage.tsx, Kiwes/src/pages/profileSetting/IntroduceSettingPage.tsx, Kiwes/src/pages/profileSetting/NickNameSettingPage.tsx, Kiwes/src/pages/profileSetting/ProfileImageSettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> font&ChatRoom

Kiwes/src/components/alarm/AlarmComponent.tsx, Kiwes/src/components/alarm/AlarmList.tsx, Kiwes/src/components/alarm/ApprovalList.tsx, Kiwes/src/components/alarm/ApprovalRequst.tsx, Kiwes/src/components/alarm/ClubApproval.tsx, Kiwes/src/components/alarm/RequestList.tsx, Kiwes/src/components/alarm/WaitingList.tsx, Kiwes/src/components/clubdetail/ClubDetailSettingModal.tsx, Kiwes/src/components/clubdetail/QnAList.tsx, Kiwes/src/components/clubdetail/ReivewErrorModal.tsx, Kiwes/src/components/clubdetail/ReviewList.tsx, Kiwes/src/pages/AlarmPage.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/WishPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:fontsize

Kiwes/src/components/clubdetail/renderLocationDetail.tsx, Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/components/search/searchBtn.tsx, Kiwes/src/pages/ChatMain.tsx, Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/pages/Home.tsx, Kiwes/src/pages/Login.tsx, Kiwes/src/pages/Search.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Fix banner and login and searc error

Kiwes/src/components/clubdetail/renderLocationDetail.tsx, Kiwes/src/pages/ChatRoom.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Complete to solve chat issue

Kiwes/src/components/clubdetail/renderLocationDetail.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/CorrectionPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:renderLocation

Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/components/post/SetupDetail1.tsx, Kiwes/src/components/post/SetupDetail2.tsx, Kiwes/src/components/post/SetupDetail3.tsx, Kiwes/src/components/post/SetupLayout.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/CorrectionPage.tsx, Kiwes/src/pages/PostClub.tsx, Kiwes/src/pages/Search.tsx, Kiwes/src/pages/SettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat:correctionPage

Kiwes/src/components/club/ClubList.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:categoryCSS&heartMappingClubDetail

Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/pages/MyPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Add create room chatting api

Kiwes/src/components/alarm/AlarmComponent.tsx, Kiwes/src/components/alarm/ApprovalModal.tsx, Kiwes/src/components/alarm/ClubApproval.tsx, Kiwes/src/components/layout/AlarmStack.tsx, Kiwes/src/components/layout/HomeStack.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:mainHeart

Kiwes/src/components/myBubbleLongpressModal.tsx, Kiwes/src/components/otherBubbleLongpressModal.tsx, Kiwes/src/pages/ChatBubbleMine.tsx, Kiwes/src/pages/ChatBubbleOther.tsx, Kiwes/src/pages/ChatMain.tsx, Kiwes/src/pages/ChatRoom.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> chatNoticeSetting

Kiwes/src/pages/SettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:setting

Kiwes/src/components/alarm/RequestList.tsx, Kiwes/src/components/layout/AlarmStack.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat:issuse

Kiwes/android/build.gradle, Kiwes/android/gradle.properties
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Change build data

Kiwes/android/app/src/debug/AndroidManifest.xml, Kiwes/package-lock.json, Kiwes/package.json, Kiwes/src/components/post/SetupDetail3.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Login.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: 전체 페이지 오류 확인

Kiwes/src/components/NothingShow.tsx, Kiwes/src/components/atoms/Text.tsx, Kiwes/src/components/clubdetail/QnAList.tsx, Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/components/post/SetupCategory.tsx, Kiwes/src/components/post/SetupDetail1.tsx, Kiwes/src/components/post/SetupDetail2.tsx, Kiwes/src/components/post/SetupDetail3.tsx, Kiwes/src/components/post/SetupLang.tsx, Kiwes/src/pages/ChatMain.tsx, Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Login.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/OtherUserPage.tsx, Kiwes/src/pages/ProfileSettingPage.tsx, Kiwes/src/pages/basicSetting/NationDetailSettingPage.tsx, Kiwes/src/pages/basicSetting/NationSettingPage.tsx, Kiwes/src/pages/profileSetting/BirthdaySettingPage.tsx, Kiwes/src/pages/profileSetting/IntroduceSettingPage.tsx, Kiwes/src/pages/profileSetting/NickNameSettingPage.tsx, Kiwes/src/pages/profileSetting/ProfileImageSettingPage.tsx, Kiwes/src/slice/LanguageSlice.ts, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> Translate ko to en

Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> Translate message

Kiwes/src/components/NothingDefault.tsx, Kiwes/src/components/NothingShow.tsx, Kiwes/src/components/alarm/ApprovalModal.tsx, Kiwes/src/components/alarm/ClubApproval.tsx, Kiwes/src/components/atoms/Text.tsx, Kiwes/src/components/club/ClubListDetail.tsx, Kiwes/src/components/clubdetail/QnAList.tsx, Kiwes/src/components/clubdetail/ReviewList.tsx, Kiwes/src/components/kickedOutModal.tsx, Kiwes/src/components/post/SetupDetail2.tsx, Kiwes/src/components/search/SearchHeader.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Success to Edit all

Kiwes/src/pages/ClubDetail.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Success to change clubdetail page

Kiwes/src/components/BoardDefaultList.tsx, Kiwes/src/components/club/ClubList.tsx, Kiwes/src/components/club/ClubListDetail.tsx, Kiwes/src/components/layout/HomeStack.tsx, Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/components/post/SetupCategory.tsx, Kiwes/src/components/post/SetupDetail2.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx, Kiwes/src/pages/LanguageSelectPage.tsx, Kiwes/src/pages/Login.tsx, Kiwes/src/pages/WishPage.tsx, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Change share icon

Kiwes/src/components/post/PostClubStep.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:clubCorrectionImage

Kiwes/src/pages/ClubDetail.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:clubDetailRefresh

Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Home & ClubDetail Swiper 및 언어 수정

Kiwes/src/pages/ChatBubbleMine.tsx, Kiwes/src/pages/ChatBubbleOther.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> chatBubbleLongPressModal Position correction

Kiwes/src/components/club/ClubListDetail.tsx, Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/components/post/SetupDetail2.tsx, Kiwes/src/pages/Home.tsx, Kiwes/src/pages/PostClub.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Edit club create logic

Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Home pagination 수정

Kiwes/src/components/post/SetupDetail2.tsx, Kiwes/src/pages/profileSetting/GenderSettingPage.tsx, Kiwes/src/pages/profileSetting/IntroduceSettingPage.tsx, Kiwes/src/pages/profileSetting/NickNameSettingPage.tsx, Kiwes/src/pages/profileSetting/ProfileImageSettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat:Deployment Version 1

Kiwes/android/app/build.gradle, Kiwes/android/app/src/main/AndroidManifest.xml, Kiwes/android/app/src/main/java/com/kiwes/MainApplication.java
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:versionBuild

Kiwes/src/components/LogoutModal.tsx, Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/pages/LanguageSelectPage.tsx, Kiwes/src/pages/Login.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/profileSetting/IntroduceSettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> Login & MyPage Image

Kiwes/src/components/atoms/Text.tsx, Kiwes/src/components/clubdetail/ReviewList.tsx, Kiwes/src/components/post/SetupCategory.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Change text color

Kiwes/android/app/build.gradle
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> Deployment 1.03

Kiwes/src/components/BoardDefaultList.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: 카테고리별, 언어별 상세 모임 하트 임시 삭제

Kiwes/src/components/LogoutModal.tsx, Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/pages/CorrectionPage.tsx, Kiwes/src/pages/PostClub.tsx, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Edit error

Kiwes/src/components/ProfileImageUploadModal.tsx, Kiwes/src/components/layout/DefaultStack.tsx, Kiwes/src/components/post/SetupDetail3.tsx, Kiwes/src/global.ts, Kiwes/src/pages/LanguageSelectPage.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/ProfileSettingPage.tsx, Kiwes/src/pages/SettingPage.tsx, Kiwes/src/pages/basicSetting/InterestTopicSettingPage.tsx, Kiwes/src/pages/profileSetting/NickNameSettingPage.tsx, Kiwes/src/pages/profileSetting/ProfileImageSettingPage.tsx, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> profileSetting issue

Kiwes/src/components/BoardList.tsx, Kiwes/src/components/club/ClubListDetail.tsx, Kiwes/src/pages/Home.tsx, Kiwes/src/pages/Search.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:recommand&search

Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> 자동슬라이드 문제 해결 및 모집마감 기준 변경

Kiwes/src/components/NothingShow.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> 이미지 사이즈 조정

Kiwes/src/components/NothingShow.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> refactor: NothingShow 이미지 크기 수정

Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/ProfileSettingPage.tsx, Kiwes/src/pages/profileSetting/ProfileImageSettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> setting profileImage to basic Image

Kiwes/src/components/club/ClubListDetail.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> feat: Change home category and language swiper height

Kiwes/src/components/alarm/AlarmList.tsx, Kiwes/src/components/alarm/ApprovalRequst.tsx, Kiwes/src/components/clubdetail/QnAList.tsx, Kiwes/src/pages/ClubDetail.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:clubdetail,Qna

Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> refactor: 추천 모임 데이터 분리

Kiwes/android/app/build.gradle, Kiwes/src/components/alarm/RequestList.tsx, Kiwes/src/pages/ClubDetail.tsx, Kiwes/src/pages/Home.tsx, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> hotfix:heart,requestNav

Kiwes/src/components/alarm/AlarmComponent.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:requestline

Kiwes/android/app/build.gradle, Kiwes/android/build.gradle
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:versionName

Kiwes/src/pages/Home.tsx, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Css err and translate

Kiwes/src/pages/Home.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix: Bannerimage 속성 변경

Kiwes/src/components/ChatRoomEnterModal.tsx, Kiwes/src/components/ProfileImageUploadModal.tsx, Kiwes/src/components/myBubbleLongpressModal.tsx, Kiwes/src/components/otherBubbleLongpressModal.tsx, Kiwes/src/components/post/PostClubStep.tsx, Kiwes/src/pages/ChatBubbleMine.tsx, Kiwes/src/pages/ChatBubbleOther.tsx, Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/pages/MyPage.tsx, Kiwes/src/pages/ProfileSettingPage.tsx, Kiwes/src/utils/utils.ts
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> MyPage css issue

Kiwes/src/pages/ReviewBubble.tsx, Kiwes/src/pages/ReviewPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> fix:reviewCSS

Kiwes/src/pages/ChatRoom.tsx, Kiwes/src/pages/profileSetting/ProfileImageSettingPage.tsx
- 내용을 입력해주세요
---
- 내용을 입력해주세요
---
---
- 내용을 입력해주세요
=> ChatRoom css issue
